AWSTemplateFormatVersion: 2010-09-09
Description: DataLake Infrastructure Setup Template
Parameters:
  EnvironmentPrefix:
    Type: String
    Default: dev
    Description: Prefix for Env Name
  CustomResourceLambdaExecutionRoleArn:
    Type: String
    Description: Custom Resource Lambda Execution Role Arn.

Resources:

  RedshiftKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: !Sub "This is ${EnvironmentPrefix} environment customer managed CMK for Redshift Data at rest encrytion."
      EnableKeyRotation: true
      Enabled: true
      KeyPolicy:
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref CustomResourceLambdaExecutionRoleArn
            Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          -
            Effect: Allow
            Sid: Allow administration of the key
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - "kms:*"
            Resource: "*"
      PendingWindowInDays: 7

Outputs:
  RedshiftKey:
    Description: Redshift KMS Key
    Value: !Ref RedshiftKey
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RedshiftKey"
