AWSTemplateFormatVersion: 2010-09-09
Description: AWS resources for the secrets to be created for Payment service.
Parameters:
  EnvironmentPrefix:
    Type: String
    Default: dev
    Description: Environment Prefix for resourcs
  MambuUsername:
    Description: Mambu UserName.
    NoEcho: 'true'
    Type: String
  MambuPassword:
    Description: Mambu Password.
    NoEcho: 'true'
    Type: String
  TruNarrativeCredential:
    Description: TruNarrative Credential.
    NoEcho: 'true'
    Type: String
  ClearBankCredential:
    Description: ClearBank Credential.
    NoEcho: 'true'
    Type: String
  ClearBankAccount:
    Description: ClearBank Account.
    NoEcho: 'true'
    Type: String
  ClearBankPublicKey:
    Description: ClearBank Public Key.
    NoEcho: 'true'
    Type: String
  NodeInstanceRole:
    Type: String
    Description: Input the ARN of the node instance role of nodes in EKS cluster for this environment
  SecretKey:
    Type: String
    Description: ID of secret key
Resources:
  MambuCredentialsSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: Mambu account username and password to be used by services
      KmsKeyId: !Ref SecretKey
      SecretString: !Sub '{ "UserName": "${MambuUsername}", "Password": "${MambuPassword}" }'
      Name: !Sub '${EnvironmentPrefix}-Mambu-Credentials'

  MambuCredentialsResourcePolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref MambuCredentialsSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref NodeInstanceRole
          Action: secretsmanager:GetSecretValue
          Resource: !Ref MambuCredentialsSecret

  TruNarativeSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "This is a Secrets Manager entry for TruNarrative credential"
      KmsKeyId: !Ref SecretKey
      Name: !Sub '${EnvironmentPrefix}-TruNarrative-Credential'
      SecretString: !Ref "TruNarrativeCredential"
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-TruNarrative-Credential'

  TruNarativeSecretResourcePolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref TruNarativeSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref NodeInstanceRole
          Action: secretsmanager:GetSecretValue
          Resource: !Ref TruNarativeSecret

  ClearBankSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "This is a Secrets Manager entry for ClearBank credential"
      KmsKeyId: !Ref SecretKey
      Name: !Sub '${EnvironmentPrefix}-ClearBank-Credential'
      SecretString: !Ref "ClearBankCredential"
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-ClearBank-Credential'

  ClearBankSecretResourcePolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref ClearBankSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref NodeInstanceRole
          Action: secretsmanager:GetSecretValue
          Resource: !Ref ClearBankSecret

  ClearBankAccountSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "This is a Secrets Manager entry for ClearBank Account"
      KmsKeyId: !Ref SecretKey
      Name: !Sub '${EnvironmentPrefix}-ClearBank-AccountId'
      SecretString: !Ref "ClearBankAccount"
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-ClearBank-AccountId'

  ClearBankAccountSecretResourcePolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref ClearBankAccountSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref NodeInstanceRole
          Action: secretsmanager:GetSecretValue
          Resource: !Ref ClearBankAccountSecret

  ClearBankPublicKeySecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "This is a Secrets Manager entry for ClearBank Public Key"
      Name: !Sub '${EnvironmentPrefix}-ClearBank-PublicKey'
      KmsKeyId: !Ref SecretKey
      SecretString: !Ref "ClearBankPublicKey"
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentPrefix}-ClearBank-PublicKey'

  ClearBankPublicKeySecretResourcePolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref ClearBankPublicKeySecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref NodeInstanceRole
          Action: secretsmanager:GetSecretValue
          Resource: !Ref ClearBankPublicKeySecret

Outputs:
  MambuCredentialsSecret:
    Value: !Ref MambuCredentialsSecret
  TruNarativeSecret:
    Value: !Ref TruNarativeSecret
  ClearBankSecret:
    Value: !Ref ClearBankSecret
  ClearBankAccountSecret:
    Value: !Ref ClearBankAccountSecret
  ClearBankPublicKeySecret:
    Value: !Ref ClearBankPublicKeySecret
