AWSTemplateFormatVersion: 2010-09-09
Description: EFS Backup Infrastructure Setup Template
Parameters:
  EnvironmentPrefix:
    Type: String
    Default: cicd
    Description: Prefix for Env Name

Resources:
    KMSKey:
      Type: AWS::KMS::Key
      Properties:
        Description: "Encryption key for efs weekly backup store"
        EnableKeyRotation: True
        Enabled: True
        KeyPolicy:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Principal:
              "AWS": { "Fn::Sub": "arn:${AWS::Partition}:iam::${AWS::AccountId}:root" }
            Action:
            - kms:*
            Resource: "*"

    BackupVaultWithDailyBackups:
      Type: "AWS::Backup::BackupVault"
      Properties:
        BackupVaultName: "BackupVaultWithWeeklyBackups"
        EncryptionKeyArn: !GetAtt KMSKey.Arn

Outputs:
  BackupVaultArn:
    Description: Backup VaultArn
    Value: !GetAtt BackupVaultWithDailyBackups.BackupVaultArn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-BackupVaultArn"
